title: Lorenzo Gurri
email: gurril@rpi.edu
description: >- # this means to ignore newlines until "baseurl:"
  A small site for documenting my journey through
  the field of cyber security and computer scince
baseurl: ""
url: "https://lorenzogurri.github.io"
github_username: lorenzogurri
repository: lorenzogurri/lorenzogurri.github.io
remote_theme: "mmistakes/minimal-mistakes@4.22.0"

# minimal-mistakes skin
minimal_mistakes_skin: "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

plugins:
  - jekyll-feed
  - jekyll-include-cache

include: ["_pages"]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

exclude:
  - Gemfile
  - Gemfile.lock
